baseURL =  "https://bibaijin.github.io/wiki/"
languageCode = "zh"
title = "Wiki | 金比白"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
publishDir = "docs"
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "金比白"
	description = "金比白的 Wiki"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/bibaijin/wiki"

	version = "0.2.0"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    primary = "teal"
    accent  = "red"

  [params.font]
    text = "Roboto"
    code = "Roboto Mono"


[social]
	twitter = ""
	github  = "bibaijin"
	email   = "bibaijin@gmail.com"


[[menu.main]]
	name   = "金比白的 Wiki"
	url    = "/"
	weight = 0

[[menu.main]]
	name   = "Bootstrap"
	url    = "bootstrap/"
	weight = 10

[[menu.main]]
	name   = "fish"
	url    = "fish/"
	weight = 20

[[menu.main]]
	name   = "Go"
	url    = "go/"
	weight = 30

[[menu.main]]
	name   = "Hugo"
	url    = "hugo/"
	weight = 40

[[menu.main]]
	name   = "Linux"
	url    = "linux/"
	weight = 50

[[menu.main]]
	name   = "Spacemacs"
	url    = "spacemacs/"
	weight = 60

[[menu.main]]
	name   = "Vagrant"
	url    = "vagrant/"
	weight = 70

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true