baseURL =  "https://bibaijin.github.io/my-wiki"
languageCode = "zh"
title = "My Wiki"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
publishDir = "docs"
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "bibaijin"
	description = "My wiki."

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/bibaijin/my-wiki"

	version = "0.1.0"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    primary = "teal"
    accent  = "red"

  [params.font]
    text = "Ubuntu"
    code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "bibaijin"
	email   = "bibaijin@gmail.com"


[[menu.main]]
	name   = "My Wiki"
	url    = "/"
	weight = 0

[[menu.main]]
	name   = "Bootstrap"
	url    = "bootstrap/"
	weight = 10

[[menu.main]]
	name   = "Go"
	url    = "go/"
	weight = 20

[[menu.main]]
	name   = "Hugo"
	url    = "hugo/"
	weight = 30

[[menu.main]]
	name   = "Linux"
	url    = "linux/"
	weight = 40

[[menu.main]]
	name   = "Spacemacs"
	url    = "spacemacs/"
	weight = 50

[[menu.main]]
	name   = "Vagrant"
	url    = "vagrant/"
	weight = 60

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true